[package]
name = "search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opener = "0.6.1"
shellexpand = "3.1.0"
termion = "3.0.0"
url = "2.5.0"
urlencoding = "2.1.3"
